# Usa la imagen base de Node.js
FROM node:20-alpine

# Crea el directorio de trabajo
WORKDIR /app

# Copia los archivos de dependencias
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código
COPY . .

# Exponer el puerto, si aplica
EXPOSE 3000

# Inicia el bot
CMD ["node", "index.js"]
